name: network-manager
version: '1.10.6'
version-script: |
    echo $SNAPCRAFT_PROJECT_VERSION-$(date +%Y%m%d)+$(git rev-parse --short HEAD)
summary: Network Manager
description: |
  NetworkManager is a system network service that manages your network
  devices and connections, attempting to keep active network connectivity
  when available. It manages ethernet, WiFi, mobile broadband (WWAN) and
  PPPoE devices, provides VPN integration with a variety of different
  VPN serivces.
  Please find the source code at: https://code.launchpad.net/~network-manager/network-manager/+git/ubuntu/+ref/snap-1.10
base: core18
confinement: strict
grade: stable

slots:
  service: network-manager

plugs:
  nmcli: network-manager
  wpa:
    interface: dbus
    bus: system
    name: fi.w1.wpa_supplicant1

hooks:
  configure:
    plugs:
      - nmcli
      - network-setup-control
apps:
  nmcli:
    command: usr/bin/nmcli
    plugs: [nmcli]
  networkmanager:
    command: bin/networkmanager
    daemon: simple
    slots: [service]
    plugs: [modem-manager, ppp, network-setup-observe, wpa, firewall-control]
    # FIXME: This will create currently a symlink inside /snap/bin
    # which points nowhere as the service isn't exposed as application
    # for the user. Instead snapd needs to gain support to handle
    # aliases for services differently by adding the Alias= option
    # within the systemd unit file instead for example. Until this
    # is implemented we keep the alias disabled.
    #
    # aliases: [NetworkManager]

parts:
  #hooks:
  #  plugin: dump
  #  source: hooks
  #  organize:
  #    configure: meta/hooks/configure
  networkmanager-common:
    plugin: dump
    source: snap-common
  #
  # TODO: investigate whether this HACK is still needed. The script
  # dhcp-lease-mover relies on inotifywait to determine if any DHCP
  # DHCP leases stored under $SNAP_DATA are created or modified, and
  # if so, it triggers a copy of the files to /run/NetworkManager/dhcp.
  # This is done so that subiquity's hardware probing tool (probert) is
  # able to detect active leases.
  #
  #inotify-tools:
  #  plugin: nil
  #  stage-packages:
  #    - libinotifytools0
  #    - inotify-tools
  #  filesets:
  #    wanted:
  #      - usr/share/doc/inotify-tools/copyright
  #      - usr/bin/inotifywait
  #      - usr/share/doc/libinotifytools0/copyright
  #      - usr/lib/libinotifytools.so.0.4.1
  #      - usr/lib/libinotifytools.so.0
  #  snap:
  #    - $wanted
  networkmanager:
    plugin: autotools
    source: .
    build-attributes: [no-system-libraries]
    build-packages:
      - intltool
      - libdbus-glib-1-dev
      - libdbus-1-dev
      - libglib2.0-dev
      - libiw-dev
      - libnl-3-dev
      - libnl-route-3-dev
      - libnl-genl-3-dev
      - ppp-dev
      - libgnutls28-dev
      - uuid-dev
      - systemd
      - libsystemd-dev
      - libudev-dev
      - libgirepository1.0-dev
      - gobject-introspection
      - python-gi
      - libpsl-dev
      - libcurl4-gnutls-dev
      - perl
      - libyaml-perl
      - libglib2.0-doc
      - libmm-glib-dev
      - libndp-dev
      - libreadline-dev
      - libnewt-dev
      - libteam-dev
      - libjansson-dev
      - dbus
      - python-dbus
      - quilt
      - xsltproc
    configflags:
      - --prefix=/usr
      - --libdir=/usr/lib
      - --disable-qt
      # dhcp handled by systemd client
      - --with-dhcpcd=no
      - --with-dhclient=no
      - --with-dnsmasq=no
      - --with-systemd-journal=yes
      # from 1.10 deb:
      - --libexecdir=/usr/lib/NetworkManager
      - --with-pppd=/usr/sbin/pppd
      - --with-resolvconf=no
      #
      # TODO: iptables & dnsmasq are used for AP mode; not
      # currently supported by the snap:
      # - --with-iptables=/sbin/iptables
      # - --with-dnsmasq=/usr/sbin/dnsmasq
      - --with-dnssec-trigger=/usr/lib/dnssec-trigger/dnssec-trigger-script
      - --with-systemdsystemunitdir=/lib/systemd/system
      - --with-udev-dir=/lib/udev
      - --with-crypto=gnutls
      # Explicitly disable session tracking, as it's not applicable on Ubuntu Core
      - --with-session-tracking=no
      - --with-suspend-resume=systemd
      - --with-modem-manager-1
      - --with-nmtui=yes
      - --with-nmcli=yes
      - --with-selinux=no
      - --with-tests
      - --with-libaudit=no
      - --without-dhcpcanon
      # Explicitly disable polkit, as it's not applicable on Ubuntu Core
      - --disable-polkit
      - --disable-polkit-agent
      - --enable-ppp
      - --enable-ifupdown
      - --disable-config-plugin-ibft
      - --enable-introspection
      - --disable-gtk-doc
      - --enable-concheck
      - --enable-teamdctl
      - --enable-json-validation
      - --disable-more-warnings
      - --disable-modify-system
      - --disable-ovs
    override-build: |
      echo "networkmanager override-build called <patches go here>"
      export QUILT_PATCHES=debian/patches
      quilt push -a
      snapcraftctl build

      # Run all tests NetworkManager ships by default
      make check
    stage-packages:
      - libasn1-8-heimdal
      - libdbus-glib-1-2
      - libcurl3-gnutls
      - libgssapi3-heimdal
      - libgssapi-krb5-2
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libidn2-0
      - libjansson4
      - libkeyutils1
      - libkrb5-3
      - libkrb5-26-heimdal
      - libkrb5support0
      - libk5crypto3
      - libldap-2.4-2
      - libmm-glib0
      - libnghttp2-14
      - libroken18-heimdal
      - libndp0
      - libpsl5
      - libreadline7
      - librtmp1
      - libsasl2-2
      - libteamdctl0
      - libunistring2
      - libblkid1
      - libgcrypt20
      - libgpg-error0
      - liblzma5
      - libmount1
      - libnl-3-200
      - libpcre3
      - libselinux1
      - libtinfo5
      - libuuid1
      - zlib1g
      - libgmp10
      - libgnutls30
      - libhogweed4
      - liblz4-1
      - libnettle6
      - libp11-kit0
      - libtasn1-6
      - libwind0-heimdal

    # Filter files pulled in by stage-packages so they aren't
    # included in the final snap. We only need them to build
    # NetworkManager. All runtime dependencies are pulled in with
    # the rdepends part below. The only left items specified
    # here are the results of the network manager build.
    filesets:
      binaries:
        - usr/bin/nmcli
        - usr/lib/*/NetworkManager
        # TODO: figure out pppd
        #- usr/lib/pppd/2.4.5/nm-pppd-plugin.so
        - usr/lib/NetworkManager
        - usr/sbin/NetworkManager
        - usr/lib/*/libnm-*
      configs:
        - etc/NetworkManager/*
      docs:
        - usr/share/doc
      rdepends:
        - lib64/*
        - lib/*/
        - usr/lib/*
      unwanted:
        # We don't want anything in usr/share but the doc folder
        # to carry all copyright information
        - -usr/share/bash-completion
        - -usr/share/bug
        - -usr/share/dbus-1
        - -usr/share/gir-1.0
        - -usr/share/glib-2.0
        - -usr/share/gtk-doc
        - -usr/share/lintian
        - -usr/share/locale
        - -usr/share/man
        - -usr/share/pam-configs
        - -usr/share/polkit-1
        - -usr/share/upstart

        # We don't use dhclient so we don't need this helper
        - -usr/lib/NetworkManager/nm-dhcp-helper
        # Things we don't support yet and don't have to ship
        - -usr/lib/NetworkManager/libnm-device-plugin-adsl.so
        - -usr/lib/NetworkManager/libnm-device-plugin-bluetooth.so

        # Unwanted content coming from the stage debian packages
        - -etc/
        # Contains many libraries which are already present in usr/lib/
        - -lib/
        - -usr/include/
        - -usr/etc
        - -usr/sbin/invoke-rc.d
        - -usr/sbin/service
        - -usr/sbin/update-rc.d
        - -usr/lib/dbus-1.0/
        - -usr/lib/tmpfiles.d/
        - -usr/lib/*/pkgconfig
        - -usr/lib/pkgconfig
        - -usr/lib/gcc/
        - -usr/lib/*/gconv/
        - -usr/lib/girepository-1.0/
        - -usr/lib/systemd/
        - -usr/lib/udev/
        - -usr/lib/*.a
        - -usr/lib/*/*.a
        - -usr/lib/*.la
        - -usr/lib/*/*.la
        - -usr/lib/*/*.o
        - -usr/lib/*/systemd-shim
        - -usr/lib/*/systemd-shim-cgroup-release-agent
    prime:
      - $binaries
      - $configs
      - $docs
      - $rdepends
      - $unwanted

  

