name: network-manager
version: 1.10.6-2-dev
version-script: |
    echo $SNAPCRAFT_PROJECT_VERSION-$(date +%Y%m%d)+$(git rev-parse --short HEAD)
summary: Network Manager
description: |
  NetworkManager is a system network service that manages your network
  devices and connections, attempting to keep active network connectivity
  when available. It manages ethernet, WiFi, mobile broadband (WWAN) and
  PPPoE devices, provides VPN integration with a variety of different
  VPN serivces.
  Please find the source code at: https://code.launchpad.net/~network-manager/network-manager/+git/ubuntu/+ref/snap-1.10
base: core18
confinement: strict
grade: stable

slots:
  service: network-manager

plugs:
  nmcli: network-manager
  wpa:
    interface: dbus
    bus: system
    name: fi.w1.wpa_supplicant1

hooks:
  configure:
    plugs:
      # network is needed to avoid some denials when using snapctl
      - network
      - network-setup-observe
apps:
  nmcli:
    command: usr/bin/nmcli
    plugs: [nmcli]
  nmtui:
    command: usr/bin/nmtui
    plugs: [nmcli]
  nmtui-connect:
    command: usr/bin/nmtui-connect
    plugs: [nmcli]
  nmtui-edit:
    command: usr/bin/nmtui-edit
    plugs: [nmcli]
  nmtui-hostname:
    command: usr/bin/nmtui-hostname
    plugs: [nmcli]
  networkmanager:
    command: bin/networkmanager
    daemon: simple
    slots: [service]
    plugs: [modem-manager, ppp, network-setup-observe, wpa, firewall-control, hardware-observe, kernel-module-control]

layout:
  /usr/lib/x86_64-linux-gnu/xtables:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/xtables

parts:
  networkmanager-common:
    plugin: dump
    source: snap-common

  dnsmasq:
    plugin: make
    source: https://git.launchpad.net/ubuntu/+source/dnsmasq
    source-type: git
    source-branch: applied/ubuntu/bionic
    build-packages:
      - build-essential
    make-parameters:
      - PREFIX=/
    override-build: |
      git apply ../../../snap-patch/dnsmasq.patch
      snapcraftctl build
    filesets:
      binaries:
        - sbin/dnsmasq
    prime:
      - $binaries

  #
  # TODO: investigate whether this HACK is still needed. The script
  # dhcp-lease-mover relies on inotifywait to determine if any DHCP
  # DHCP leases stored under $SNAP_DATA are created or modified, and
  # if so, it triggers a copy of the files to /run/NetworkManager/dhcp.
  # This is done so that subiquity's hardware probing tool (probert) is
  # able to detect active leases.
  #
  #inotify-tools:
  #  plugin: nil
  #  stage-packages:
  #    - libinotifytools0
  #    - inotify-tools
  #  filesets:
  #    wanted:
  #      - usr/share/doc/inotify-tools/copyright
  #      - usr/bin/inotifywait
  #      - usr/share/doc/libinotifytools0/copyright
  #      - usr/lib/libinotifytools.so.0.4.1
  #      - usr/lib/libinotifytools.so.0
  #  snap:
  #    - $wanted
  networkmanager:
    plugin: autotools
    source: .
    build-packages:
      - intltool
      - libdbus-glib-1-dev
      - libdbus-1-dev
      - libglib2.0-dev
      - libiw-dev
      - libnl-3-dev
      - libnl-route-3-dev
      - libnl-genl-3-dev
      - ppp-dev
      - libgnutls28-dev
      - uuid-dev
      - systemd
      - libsystemd-dev
      - libudev-dev
      - libgirepository1.0-dev
      - gobject-introspection
      - python-gi
      - libpsl-dev
      - libcurl4-gnutls-dev
      - perl
      - libyaml-perl
      - libglib2.0-doc
      - libmm-glib-dev
      - libndp-dev
      - libreadline-dev
      - libnewt-dev
      - libteam-dev
      - libjansson-dev
      - dbus
      - python-dbus
      - quilt
      - xsltproc
      - iptables
      - gtk-doc-tools
    configflags:
      - --prefix=/usr
      - --libdir=/usr/lib
      - --disable-qt
      # dhcp handled by systemd client
      - --with-dhcpcd=no
      - --with-dhclient=no
      - --with-dnsmasq=no
      - --with-iptables=/snap/$SNAPCRAFT_PROJECT_NAME/current/sbin/iptables
      - --with-systemd-journal=yes
      - --libexecdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/NetworkManager
      - --with-pppd=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/sbin/pppd
      - --with-resolvconf=/snap/$SNAPCRAFT_PROJECT_NAME/current/sbin/resolvconf
      #
      # TODO: dnsmasq is used for AP mode; not
      # currently supported by the snap:
      # - --with-dnsmasq=/usr/sbin/dnsmasq
      - --with-dnssec-trigger=/usr/lib/dnssec-trigger/dnssec-trigger-script
      - --with-systemdsystemunitdir=/lib/systemd/system
      - --with-udev-dir=/lib/udev
      - --with-crypto=gnutls
      # Explicitly disable session tracking, as it's not applicable on Ubuntu Core
      - --with-session-tracking=no
      - --with-suspend-resume=systemd
      - --with-modem-manager-1
      - --with-nmtui=yes
      - --with-nmcli=yes
      - --with-selinux=no
      - --with-tests
      - --with-libaudit=no
      - --without-dhcpcanon
      # Explicitly disable polkit, as it's not applicable on Ubuntu Core
      - --disable-polkit
      - --disable-polkit-agent
      - --enable-ppp
      - --enable-ifupdown
      - --disable-config-plugin-ibft
      - --enable-introspection
      - --disable-gtk-doc
      - --enable-concheck
      - --enable-teamdctl
      - --enable-json-validation
      - --disable-more-warnings
      - --disable-modify-system
      - --disable-ovs
      # Set explicitly CFLAGS until lp: #1791946 is solved
      - CFLAGS=-O2
    override-build: |
      echo "networkmanager override-build called <patches go here>"
      export QUILT_PATCHES=debian/patches
      quilt push -a

      # remove configure to trigger autotools
      rm ./configure
      snapcraftctl build

      # Run all tests NetworkManager ships by default
      make check
    stage-packages:
      - iptables
      - iputils-arping
      - libasn1-8-heimdal
      - libdbus-glib-1-2
      - libcurl3-gnutls
      - libgssapi3-heimdal
      - libgssapi-krb5-2
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libidn2-0
      - libjansson4
      - libkeyutils1
      - libkrb5-3
      - libkrb5-26-heimdal
      - libkrb5support0
      - libk5crypto3
      - libldap-2.4-2
      - libmm-glib0
      - libnewt0.52
      - libnghttp2-14
      - libroken18-heimdal
      - libndp0
      - libpsl5
      - libreadline7
      - librtmp1
      - libsasl2-2
      - libteamdctl0
      - libunistring2
      - libblkid1
      - libgcrypt20
      - libgpg-error0
      - liblzma5
      - libmount1
      - libnl-3-200
      - libpcre3
      - libselinux1
      - libuuid1
      - zlib1g
      - libgmp10
      - libgnutls30
      - libhogweed4
      - liblz4-1
      - libnettle6
      - libp11-kit0
      - libslang2
      - libtasn1-6
      - libwind0-heimdal
      - ppp
      - resolvconf

    override-stage: |
      snapcraftctl stage
      patch -p1 < "$SNAPCRAFT_PART_SRC"/snap-patch/resolvconf.patch

    # Filter files pulled in by stage-packages so they aren't
    # included in the final snap. We only need them to build
    # NetworkManager. All runtime dependencies are pulled in with
    # the rdepends part below. The only left items specified
    # here are the results of the network manager build.
    filesets:
      binaries:
        - sbin/*tables*
        - sbin/resolvconf
        - usr/bin/arping
        - usr/bin/nmcli
        - usr/bin/nmtui
        - usr/bin/nmtui-connect
        - usr/bin/nmtui-edit
        - usr/bin/nmtui-hostname
        - usr/sbin/pppd
        - usr/lib/*/NetworkManager
        - usr/lib/pppd/2.4.5/nm-pppd-plugin.so
        - usr/lib/NetworkManager
        - usr/sbin/NetworkManager
      configs:
        - etc/NetworkManager/*
        - etc/resolvconf/update.d/libc
      docs:
        - usr/share/doc/*/copyright
      libs:
        - lib/resolvconf/list-records
        - lib/*/libnewt*
        - lib/*/libslang*
        - usr/lib/libnm*
        - usr/lib/*/libasn1*
        - usr/lib/*/libcurl-gnutls*
        - usr/lib/*/libdbus-glib*
        - usr/lib/*/libgssapi*
        - -usr/lib/*/libgssapi_krb5*
        - usr/lib/*/libhcrypto*
        - usr/lib/*/libheimbase*
        - usr/lib/*/libheimntlm*
        - usr/lib/*/libhx509*
        - usr/lib/*/libip4tc*
        - usr/lib/*/libip6tc*
        # required for teamdctl
        - usr/lib/*/libjansson*
        - usr/lib/*/libkrb5*26*
        - usr/lib/*/liblber-2.4*
        - usr/lib/*/libldap_r-2.4*
        - usr/lib/*/liblzma*
        - usr/lib/*/libmm-glib*
        - usr/lib/*/libndp*
        - usr/lib/*/libnghttp2*
        - usr/lib/*/libpcap*
        - usr/lib/*/libpsl*
        - usr/lib/*/libroken*
        - usr/lib/*/librtmp*
        - usr/lib/*/libsasl2*
        - usr/lib/*/libteamdctl*
        - usr/lib/*/libwind*
        - usr/lib/*/libxtables*
        - usr/lib/*/xtables/*
      unwanted:
        # We don't use dhclient so we don't need this helper
        - -usr/lib/NetworkManager/nm-dhcp-helper
        # Things we don't support yet and don't have to ship
        - -usr/lib/NetworkManager/libnm-device-plugin-adsl.so
        - -usr/lib/NetworkManager/libnm-device-plugin-bluetooth.so

        # Some additional build artifacts we do not need
        - -usr/lib/pkgconfig
    prime:
      - $binaries
      - $configs
      - $docs
      - $libs
      - $unwanted
