name: Publish to edge

on:
  push:
    branches:
      - snap-1.10
      - snap-20
      - snap-22

jobs:
  build:
    # self-hosted runner so we can access launchpad
    runs-on: self-hosted
    environment: beta
    steps:
      - name: Publish to edge
        env:
          LP_CREDENTIALS: ${{ secrets.LP_CREDENTIALS }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        uses: snapcore/system-snaps-cicd-tools/action-publish-edge@main
