name: Spread tests

on:
  pull_request:
    branches:
      - snap-1.10
      - snap-20
      - snap-22

jobs:
  build:
    # Need to share self hosted runners with repo
    runs-on: self-hosted
    steps:
      - name: Export credentials
        shell: bash
        env:
          LP_SYSTEM_SNAPS_CREDS: ${{ secrets.LP_SYSTEM_SNAPS_CREDS }}
        run: |
          printf "%s\n" "$LP_SYSTEM_SNAPS_CREDS" > /tmp/.launchpad.credentials
      - name: Build and test
        uses: snapcore/system-snaps-cicd-tools/action-test@main
